version: '3'
services:
  gekko:
    build: ./
    volumes:
      - CONFIG
    links:
      - redis
#      - postgresql
    environment:
     - HOST
     - PORT
     - USE_SSL
     - MEMORYNODE
     - CONFIG_EXT
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}:${PORT}"
